# NUMPY TUTORIAL CODE 

In [1]:
import numpy as np

#### To Create Numpy Array

In [2]:
myarr = np.array([3,12,24,7])

In [3]:
myarr

array([ 3, 12, 24,  7])

### To make D type

In [4]:
myarr = np.array([3,12,24,7],np.int8) #using 8 bit

In [5]:
myarr

array([ 3, 12, 24,  7], dtype=int8)

### To Access element 

In [6]:
myarr = np.array([[3,12,24,7]],np.int8)  # used to make 2D array

In [7]:
myarr[0,1]

12

### To get the shape of element 

In [8]:
myarr.shape

(1, 4)

In [9]:
myarr.dtype

dtype('int8')

 ### To change the element 

In [10]:
myarr[0,1]=28

In [11]:
myarr

array([[ 3, 28, 24,  7]], dtype=int8)

## Conversion from other Python structures

In [12]:
listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])

In [13]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [14]:
listarray.dtype


dtype('int32')

In [15]:
listarray.size

9

In [16]:
listarray.shape

(3, 3)

In [17]:
np.array({34,23,23})

array({34, 23}, dtype=object)

### Intrinsic numpy array creation objects

#### This will make an array of zeros of 2x5

In [18]:
zeros=np.zeros((2,5))

In [19]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
zeros.shape

(2, 5)

In [21]:
zeros.dtype

dtype('float64')

#### np.arange will provide array of 0 to n-1

In [22]:
rng=np.arange(20)

In [23]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### linspace provide linear space 

In [24]:
lspace=np.linspace(1,50,10)

In [25]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [26]:
lspace=np.linspace(1,4,4)

In [27]:
lspace

array([1., 2., 3., 4.])

### np.empty provide random element 

In [28]:
emp = np.empty((4,6))

In [29]:
emp

array([[8.38069993e-312, 7.70742408e-322, 0.00000000e+000,
        0.00000000e+000, 1.37961302e-306, 1.15998412e-028],
       [2.44171989e+232, 8.00801729e+159, 7.06269593e-077,
        2.99067252e-067, 1.28448408e-057, 5.51681714e-048],
       [2.36945494e-038, 1.47900214e-076, 6.35226565e-067,
        2.72827734e-057, 1.17178620e-047, 6.01347002e-154],
       [5.03278346e-038, 5.79961775e+294, 1.43267083e+161,
        4.56317366e-144, 4.82412328e+228, 1.04718130e-142]])

### empty_like 

In [30]:
emp_like = np.empty_like(lspace) 

In [31]:
emp_like

array([1., 2., 3., 4.])

### identity function : The identity array is a square array with ones on the main diagonal.

In [32]:
ide=np.identity(50)

In [33]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [34]:
ide.shape

(50, 50)

In [35]:
arr = np.arange(99)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

### to Rehsape the array 

In [37]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

### to convert it back use ravel to form 1 D array

In [38]:
arr = arr.ravel()

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [40]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [41]:
ar = np.array(x)

In [42]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [43]:
ar.sum(axis=0) #adding the columns

array([12,  8,  9])

In [44]:
ar.sum(axis=1) #adding the rows

array([ 6, 15,  8])

In [45]:
ar.T  # to transpose the axis 

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [46]:
ar.flat # to provide iteral

In [47]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [48]:
ar.ndim # provide dimension

2

In [49]:
ar.size  # provide how much element

9

In [50]:
ar.nbytes

36

### To make one D array

In [51]:
one = np.array([1,2,34,55,64])

### argmax provide highest element position

In [52]:
one.argmax()  # to run as a function 

4

### argmin provide lowest element position

In [53]:
one.argmin()

0

In [54]:
one.argsort() # indices provide that how it can sort 

array([0, 1, 2, 3, 4], dtype=int64)

In [55]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [56]:
ar.argmin()

8

In [57]:
ar.argmax()

6

In [58]:
ar.argmax(axis=0) # dealing with columns

array([2, 1, 1], dtype=int64)

In [59]:
ar.argmin(axis=1) #dealing with rows

array([0, 0, 2], dtype=int64)

In [60]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [61]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [62]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [63]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

### Performing Matrix operations 

In [64]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [65]:
ar2=np.array([[1, 2, 3],
       [4, 0, 6],
       [0, 1, 0]])

In [66]:
ar+ar2 # can perform addition

array([[ 2,  4,  6],
       [ 8,  5, 12],
       [ 7,  2,  0]])

In [67]:
ar*ar2

array([[ 1,  4,  9],
       [16,  0, 36],
       [ 0,  1,  0]])

In [68]:
np.sqrt(ar) #to find root

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [69]:
ar.sum()

29

In [70]:
ar.max()

7

In [71]:
ar.min()

0

### To find element in array

In [72]:
np.where(ar>5)  # check array and this will find that at what part it will greater than 5 in matrix

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [76]:
# to count non zeros 

np.count_nonzero(ar)

8

In [77]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [78]:
ar[1,2] = 0

In [85]:
np.nonzero(ar)


(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

### How numpy take less space

In [80]:
import sys

In [81]:
chec = [0,4,55,2]

In [82]:
np_ar = np.array(chec)

In [83]:
sys.getsizeof(1) * len(chec)

112

In [84]:
np_ar.itemsize * np_ar.size

16

In [86]:
np_ar.tolist()

[0, 4, 55, 2]